### ISSUE TITLE
Dev Ops

### ISSUE THREAD

**Issue by alextsk** [Bibigyl/FSD_task_2#1]
Начнем с развертывания
папку dist нужно убрать из мастера, пусть деплой на gh-pages будет в отдельной ветке. есть orphan branches в гите, есть плагин для вебпака
проект должен запускаться одной командой и открывать ui-kit сразу при переходе и автоматически пересобираться при изменениях
страницы сайта можно открывать по /[название-главной-страницы]
описать способ запуска и сборки в ридми проекта

**Comment by Bibigyl** [comment]
1. Во втором задании папку дист убрала, добавила плагин gh-pages. Деплой происходит по команде deploy.
В 4 задании у меня есть папка slider (переименованная dist), в ней два файла - js и css, которые нужно скачать и подключить к себе для использования плагина. Я так понимаю ее скрывать не нужно. Еще есть папка demo, здесь файлы для демо страницы. Ее нужно убирать?

2. Про одну команду не совсем поняла. У меня сейчас и там, и там, есть режимы разработки и продакшена, то есть start и build. При выполнении start в верстке открывается ui-kit, все автоматически пересобирается. В слайдере - демо страница.

3. "страницы сайта можно открывать по /[название-главной-страницы]" - сделала

4. "описать способ запуска и сборки в ридми проекта" - сделала. Проверила сборку с нуля, собирается

**Comment by alextsk** [comment]
> При выполнении start в верстке открывается ui-kit

сейчас работает, раньше не открывалось

> "страницы сайта можно открывать по /[название-главной-страницы]" - сделала

в npm run start не получается, если должно работать опиши в ридми как попасть на страницы

**Comment by alextsk** [comment]
а для чего нужен
`"temp": "webpack-dev-server --host 192.168.0.178 --mode development"`?

**Comment by alextsk** [comment]
devDependencies - это зависимости нужные только при разработке, тестовые обвязки например, какие то анализаторы 
dependencies - зависимости  без которых не получится собрать проект

**Comment by Bibigyl** [comment]
"temp" - это я уберу позже, проверяю как на мобильном открывается

**Comment by alextsk** [comment]
> "temp" - это я уберу позже, проверяю как на мобильном открывается

мы это не проверяем) 
достаточно если в браузере на разных размерах окна корректно обрабатывается

**Comment by alextsk** [comment]
ghpages.publish вызывается на каждый запуск конфига

**Comment by alextsk** [comment]
с dependencies нужен еще подход, 
ты ведь без вебпака или pug не соберешь проект, а без gh-pages например - соберешь

**Comment by alextsk** [comment]
> "temp" - это я уберу позже

мы ведь в гите,  можно сделать себе отдельную ветку для тестирования разных идей, 
давай оставим мастер образцово-показательным

**Comment by Bibigyl** [comment]
А ты мне точно правильно объяснил про devDependencies и dependencies? Мне кажется сейчас неправильно, а правильно было в предыдущем коммите. Тогда я сделала по такому принципу https://qna.habr.com/answer?answer_id=559717&_ga=2.142392946.1910299460.1576694325-2118000953.1570654831#comments_list_559717. И во всех плагинах, которые я посмотрела тоже так же, все вебпаки, бабели, лоэдеры... лежат в devDependencies
