### ISSUE TITLE
Не используемый semantic block

### ISSUE THREAD

**Issue by a-poluhin** [Bibigyl/FSD_task_2#10]
![image](https://user-images.githubusercontent.com/10168007/77394156-3a2f6b00-6dd1-11ea-974a-2d96c1984f45.png)
Не увидел чтобы этот блок появлялся в верстке. Если он действительно нигде не используется стоит избавиться от пережитка прошлого=)

**Comment by Bibigyl** [comment]
Этот блок используется только на странице юи-кита headers-and-footers https://bibigyl.github.io/FSD_task_2/headers-and-footers 
Не трогаю?

**Comment by a-poluhin** [comment]
Да оставляй=)
