### ISSUE TITLE
Почистить неиспользуемые переменные

### ISSUE THREAD

**Issue by a-poluhin** [Bibigyl/FSD_task_2#13]
![image](https://user-images.githubusercontent.com/10168007/77410463-74a70100-6ded-11ea-96c9-070641d696bd.png)

**Comment by Bibigyl** [comment]
Я все сделала, не знаю видел ты или нет. Куда мне лучше писать, когда все готово?

**Comment by a-poluhin** [comment]
Я думаю можешь на телеграмм мне писать @dusha94 =)
