### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by alextsk** [Bibigyl/FSD_task_2#3]
правки по бэм, разбиение на компоненты

**Comment by alextsk** [comment]
начнем с button, вместо case можно использовать hashmap
```
config = {'argval1': 'classname1',...}

mixin(arg,...)
  class = config[arg] || default
```

так более декларативно и в одном месте будет полный список состояний

**Comment by alextsk** [comment]
&attributes создает недетерминированное состояние, туда можно что угодно добавить

**Comment by alextsk** [comment]
&__border не элемент

**Comment by alextsk** [comment]
дефолтное состояние для всех параметров, 
`button()` должен что то отрендерить

**Comment by alextsk** [comment]
_colored - неполиткорретно) скорее filled. и тогда empty не нужен или наоборот, один из них будет дефолтным

**Comment by alextsk** [comment]
&__border {
 .button  -> родительский элемент вроде в sass можно получить через интерполяцию переменной

margin: 2px; - влияет на окружение

**Comment by alextsk** [comment]
`justify-content: center;` нужен только в` _big?`
если нет то общие правила лучше выносить в блок

`display: inline-flex;` - достаточно одного)

```
 &_colored {
    padding: 14px 20px; 
```- лучше чтобы модификатор делал что то одно, паддинг не относится к цвету, если будет другой модификатор с паддингом то результат будет зависеть от порядка, это ненадежно

**Comment by Bibigyl** [comment]
Все что связано с border - я добавила этот лишний див, чтобы сделать градиентную границу. Поэтому и предполагала его как элемент кнопки. margin в этом случае - это ширина границы

**Comment by Bibigyl** [comment]
Немного про кнопку: у меня есть 4 типа кнопки - filled, empty, textual, big. Причем у них мало общего. У кнопок filled и empty  есть два размера - стандартный и маленький, у остальных кнопок размер всегда один. У текстовых кнопок есть два цвета - цветной и серый.

**Comment by alextsk** [comment]
для ортогональных свойств можно делать >1 конфига

**Comment by Bibigyl** [comment]
Как сделала сейчас. Есть модификатор тип с двумя вариантами - filled и empty. Если не задан не один кнопка - это просто текст без заливки и границ. То, что мы обсуждали про состояние not active (в макете полупрозрачные), все таки это на hover. Для тех кнопок, где только текст - серый текст - это тоже не not active. Это просто вид кнопки, она встречается, например в дропдауне. Поэтому сейчас у такой кнопки есть два вида - яркая и серая. Filled и empty могут быть разного размера (standard или small) и растянутыми или нет (я убрала отдельный тип big, и назвала, как ты правильно подметил растянутой - extended). 
Убрала конфиг. Насколько я поняла, так как у меня нет независимых модификаторов, он не нужен. Это правильно? У меня сейчас простая текстовая кнопка не может быть растянутой или иметь размер, но это осуществимо, хоть и странно. Оставляю как есть? 
У тега button по дефолту есть заливка и паддинги. Я их обнуляю (в самом верху файла button.scss). Этот кусок нужно оставить здесь или перенести в файл reset? 

Еще в css я случайно оставила несколько закомментированных строчек, я их уже убрала

**Comment by alextsk** [comment]
'button_' + args.type -  даже если нет конфига то передавать куски класса в миксин все равно не нужно, к тому же бинарные состояние проще делать через boolean
```
mixin button({isFilled = false}) // не смотри на синтаксис, смысл в дефолт false
button({isFilled: true}) -» renders -» button.button.button__filled
```

**Comment by alextsk** [comment]
> Этот кусок нужно оставить здесь или перенести в файл reset?

здесь, без него ведь компонент не работает

**Comment by alextsk** [comment]
Advantages
кроме того что название слишком специфично, есть еще проблема
для любых списков возможно два варианта переиспользования
1 список используется с другими элементами
2 элементы используются вне списка
лучше сразу это предусматривать и делать их отдельными блоками
(не помню умеет ли pug рендерить аргументы, но как минимум блоки с картинкой точно можно вынести)

**Comment by Bibigyl** [comment]
1 список используется с другими элементами
это не поняла. с другими картинками? не с картинками material-icons. Или с текстом/без текста, с заголовком/без заголовка?

2 элементы используются вне списка
как лучше сделать - проверять что items.length > 1 и делать список в миксине. Или уже на странице, делать список и несколько раз вызывать миксин

Насчет названия - в макете это icon-text-list. Подойдет такое название?

**Comment by alextsk** [comment]
> Или уже на странице, делать список и несколько раз вызывать миксин

если делать так то 

>  icon-text-list

подойдет

**Comment by Bibigyl** [comment]
Леша, если будешь думать что дальше проверять, посмотри все варианты чекбоксов, dropdown, date-dropdown, filter-date-dropdown. Там где остаются вопросы, я пишу их прямо в файлах, позже уберу, так же как и всю помойку из комментариев которую я оставляю, потому что если она есть, скорее всего на этом моменте я остановилась.

**Comment by Bibigyl** [comment]
Есть ли в компании обязательное требование к именованию блок__элемент_имя-модификатора_модификатор? У меня сейчас везде так блок__элемент_модификатор.
Количество пробелов в отступах pug - 4, scss - 2, js - 4?
Имеет ли для тебя значение как я назову обертки в юи-кит?
И напомни, пожалуйста про кавычки - в pug - двойные, в js, css - одинарные? 
Все атрибуты в pug-файлах должны быть внутри двойных кавычек?
У меня есть файл main.scss. В него импортируются все стили, а он - непосредственно в js страниц. Еще в этом файле стили заголовков. Это допустимо? (если я правильно поняла, все стили заголовков я должна продублировать там где они встречаются, как и box-sizing: border-box; )

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/0aca3bcc82c7500b2f51295af04ea6e99b4aa634/src/common.blocks/checkbox-button/checkbox-button.pug#L13
похоже на заголовок

https://github.com/Bibigyl/FSD_task_2/blob/0aca3bcc82c7500b2f51295af04ea6e99b4aa634/src/common.blocks/checkbox-button/checkbox-button.pug#L14
а зачем?

>  Насколько я поняла, так нельзя

почему нельзя?

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/0aca3bcc82c7500b2f51295af04ea6e99b4aa634/src/common.blocks/date-dropdown/date-dropdown.pug#L7
**date**-dropdown знает маску даты, не нужно ее получать снаружи. плейсхолдер можно, он не обязан совпадать с маской

https://github.com/Bibigyl/FSD_task_2/blob/0aca3bcc82c7500b2f51295af04ea6e99b4aa634/src/common.blocks/date-dropdown/date-dropdown.pug#L35-L37
1 - нежелательно чтобы они могли неявно влиять на состояние окружения, пусть наезжают
2 - на твое усмотрение
3 - префикс js- для всех участвующих в js

**Comment by alextsk** [comment]
review__left-part - ненадежно как с button__red. сегодня она слева и красная завтра справа и синяя. нужно более общее имя
