### ISSUE TITLE
MASKED TEXT FIELD

### ISSUE THREAD

**Issue by alextsk** [Bibigyl/FSD_task_2#4]
https://github.com/Bibigyl/FSD_task_2/blob/6739c8f8183be5f905bc1709319ad4d7c78ad028/src/common.blocks/text-field/text-field.pug#L2
как видно из названия элемент не для даты, а для любого текста с маской. т.е. маска должна передаваться в аргументах

**Comment by alextsk** [comment]
//- есть id - можно ли их использовать
если только ты уверена в его уникальности, сгенерированный хеш например, передавать в аргументах не нужно
//- нужен ли label
на усмотрение, если и есть то опциональный
//- оборачивать инпут в label?
зависит от других решений, просто пустой лейбл смысла не несет
//- нужно ли использовать аттрибут type==date для masked
нет, т.к. это не дата

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/6739c8f8183be5f905bc1709319ad4d7c78ad028/src/common.blocks/text-field/text-field.scss#L32
это работает?

**Comment by Bibigyl** [comment]
1. :not(empty) {  - убрала, не помню зачем добавляла)
2. Про лейблы. Я их оставила, инпут внутри. Id убрала
3. Про маску. Все намеки на то что это маска даты убрала. js работает

**Comment by Bibigyl** [comment]
Еще раз перечитала и убрала лейблы

**Comment by Bibigyl** [comment]
Я правильно добавляю класс js-... например js-text-field? их же не нужно добавлять на каждый элемент, который задействован в коде?

Что нужно писать в catch при перехвате ошибок? Сейчас у меня там предупреждение console.warn

**Comment by alextsk** [comment]
js - на каждый который захватывается js
console.warn - норм
