### ISSUE TITLE
Minor 

### ISSUE THREAD

**Issue by alextsk** [Bibigyl/FSD_task_2#5]
https://github.com/Bibigyl/FSD_task_2/blob/15ea5db7c73ac81a73e596dd630fe234a2be1c8d/src/blocks-base/filter-date-dropdown/filter-date-dropdown.pug#L7-L8

https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/date-dropdown/date-dropdown.pug#L14-L16

дефолтные значения можно задать прямо в деструктуризации

https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/counted-item/counted-item.pug#L3-L6
магические числа

https://github.com/Bibigyl/FSD_task_2/blob/65dcbe18519aa70f969f8848d8b8296b672028e2/src/blocks-base/dropdown/dropdown.pug#L10
зачем 2 текста?

https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/counted-item/counted-item.js#L22
https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/counted-item/counted-item.js#L16
магические числа

https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/counted-item/counted-item.js#L31-L32
логические это должно быть в первой ветке ifa. 
можно сделать guard 
```
if (!четотам) {return}
...просто код
```

https://github.com/Bibigyl/FSD_task_2/blob/5462011b4a4b323f31f0fc78ac8a1fe0c094b6e9/src/blocks-base/counted-item/counted-item.js#L8
parseInt?

https://github.com/Bibigyl/FSD_task_2/blob/65dcbe18519aa70f969f8848d8b8296b672028e2/src/blocks-base/dropdown/dropdown.js#L7
200 px? sec? hrs?

https://github.com/Bibigyl/FSD_task_2/blob/65dcbe18519aa70f969f8848d8b8296b672028e2/src/blocks-base/dropdown/dropdown.js#L55
что же там в последних двух? из кода не понятно

https://github.com/Bibigyl/FSD_task_2/blob/65dcbe18519aa70f969f8848d8b8296b672028e2/src/blocks-base/dropdown/dropdown.pug#L7-L9
какой у них тип, строки или булевы?

https://github.com/Bibigyl/FSD_task_2/blob/a7218b3028b57b1ba95f9b7a534469e2ac487f41/src/scss/_vars.scss#L1-L5
имена непонятные

**Comment by Bibigyl** [comment]
Дефолтные значения в деструктуризацию
https://github.com/Bibigyl/FSD_task_2/commit/2083fc447d57f33378040c939224f6b780111a65

**Comment by Bibigyl** [comment]
Удалила числа 0 и 99 в counted-items
ParseInt вместо *1
https://github.com/Bibigyl/FSD_task_2/commit/4b3293a0a24bfa94cea94d4befff93aae53b1ed5

**Comment by Bibigyl** [comment]
>  let text = content.text || content.initialText; 
> зачем 2 текста?

initialText - это например 'Сколько гостей'
text - это например '2 спальни, 2 кровати...'
То есть initialText - когда все по нулям, text - когда что то уже выбрано.
Можно совсем убрать text и сделать item.find(button_inc).trigger(click) несколько раз
Сделать так?

**Comment by Bibigyl** [comment]
>  $dropdown.children(".js-dropdown__popup").slideToggle(200, "linear"); 
> 
> 200 px? sec? hrs?

Там же по дефолту ms. Все равно всегда нужно явно указывать?

**Comment by Bibigyl** [comment]
Проверила slideToggle, он вообще первым параметром принимает строку fast / slow или число миллисекунд. А что ты имел ввиду?

**Comment by alextsk** [comment]
> Проверила slideToggle, он вообще первым параметром принимает строку fast / slow или число миллисекунд. А что ты имел ввиду?

что это магическое число

**Comment by alextsk** [comment]
```
value = value < min ? min : value;
value = value > max ? max : value;
```

лучше через Math.min\max

`decDisabled = value == min ? 'counted-item__operation_disabled' : false;` - boolean | string

**Comment by alextsk** [comment]
js-dropdown__counted-item - не должен быть привязан ни к одному из блоков. лучше сделать его data-атрибутом

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/3d21f2b251115b866cc513c7eecaf8f849210c36/src/blocks-base/dropdown/dropdown.js#L57
возможно стоит подобрать другой способ получения данных из строки?

**Comment by alextsk** [comment]
animationDurationInMs - константы обычно uppercase и без предлогов, напр ANIMATION_MS

**Comment by alextsk** [comment]
> initialText - это например 'Сколько гостей'
> text - это например '2 спальни, 2 кровати...'
 
а я понял что этот текст уже есть в content.items, или это другой текст?

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/3d21f2b251115b866cc513c7eecaf8f849210c36/src/blocks-base/like-button/like-button.js#L6
parseint

**Comment by alextsk** [comment]
ui-logo.pug -> ui.logo.svg.pug
для всех где просто картинка

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/3d21f2b251115b866cc513c7eecaf8f849210c36/src/blocks-base/pagination/pagination.pug#L9
text можно разобрать в аргументах

**Comment by alextsk** [comment]
blocks-base/logo/ - почему в блоках? если это просто картинки то в images

**Comment by Bibigyl** [comment]
> > initialText - это например 'Сколько гостей'
> > text - это например '2 спальни, 2 кровати...'
> 
> а я понял что этот текст уже есть в content.items, или это другой текст?

Может быть другим. Я добавила text для соответствия макету 
это в макете
![image](https://user-images.githubusercontent.com/44343944/75794835-67649c80-5d82-11ea-80a5-b1ac27292b45.png)

так будет если я уберу параметр text
![image](https://user-images.githubusercontent.com/44343944/75794911-8d8a3c80-5d82-11ea-8c64-447b85c5784a.png)

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/3d21f2b251115b866cc513c7eecaf8f849210c36/src/blocks-base/rate-button/rate-button.js#L35
префикс js-

**Comment by alextsk** [comment]
```
 value = Math.max(min, value);
 value = Math.min(max, value);
```
=> 
` value = Math.min(max, Math.max(min, value));`
 и не придется перезаписывать переменную. 
вообще этого нужно избегать, кроме флажков и индексов в циклах

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_task_2/blob/dc6f706c7704cd8215906a40a02282a9092d40f9/src/blocks-base/slider-range/slider-range.js#L42
 в parseInt всегда должен быть второй параметр
